version: 2
jobs:
  debian:
    docker:
      - image: debian:latest
    working_directory: /root/wd
    steps:
      - checkout
      - run:
          command: |
            echo $CIRCLE_SHA1
  go:
    docker:
      - image: golang:latest
    working_directory: /root/wd
    steps:
      - checkout
      - run:
          command: |
            echo $CIRCLE_SHA1
workflows:
  version: 2
  build:
    jobs:
      - debian
      - go